stages: 
  - build
  - test
  - deploy

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - AWS_FUNCITONS="get-review get-new-meeting get-dashboard get-summary post-review post-new-meeting post-login post-create-account"

build:
  image: gradle:7.4.2-jdk11-alpine
  stage: build
  script: gradle build -Dorg.gradle.java.home=$JAVA_HOME

test:
  image: gradle:7.4.2-jdk11-alpine
  stage: test
  script: gradle check -Dorg.gradle.java.home=$JAVA_HOME

deploy:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  stage: deploy
  script:
    - ls
    - ls build
    - ls build/libs
    - for fun in $AWS_FUNCITONS; do aws lambda update-function-code --function-name $fun --zip-file fileb://build/libs/rivia-backend.jar; done
